name: LiXiPlugin
version: "1.0-SNAPSHOT"
main: me.typical.lixiplugin.LXPlugin
description: Give out lucky money :D
author: typical.smc
website: https://github.com/typical-smc/LiXiPlugin
api-version: "1.21"
loader: me.typical.lixiplugin.LXPluginLoader
folia-supported: true
# Optional dependencies
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
      join-classpath: true
    Nexo:
      load: BEFORE
      required: false
      join-classpath: true
    ItemsAdder:
      load: BEFORE
      required: false
      join-classpath: true

